presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    clone_uri: "git@github.com:aicoe-aiops/operate-first-jupyterhub-analysis"
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.8
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "500m"
